// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.42000
//


/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceTestSoap", Namespace="http://tempuri.org/")]
public partial class WebServiceTest : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback getUserStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback increasePhysicalStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback decreasePhysicalStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback increaseSocialStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback decreaseSocialStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback increaseMentalStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback decreaseMentalStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback increaseEmotionalStatsOperationCompleted;
    
    private System.Threading.SendOrPostCallback decreaseEmotionalStatsOperationCompleted;
    
    /// CodeRemarks
    public WebServiceTest() {
        this.Url = "http://localhost:55914/WebServiceTest.asmx";
    }
    
    /// CodeRemarks
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// CodeRemarks
    public event getUserStatsCompletedEventHandler getUserStatsCompleted;
    
    /// CodeRemarks
    public event increasePhysicalStatsCompletedEventHandler increasePhysicalStatsCompleted;
    
    /// CodeRemarks
    public event decreasePhysicalStatsCompletedEventHandler decreasePhysicalStatsCompleted;
    
    /// CodeRemarks
    public event increaseSocialStatsCompletedEventHandler increaseSocialStatsCompleted;
    
    /// CodeRemarks
    public event decreaseSocialStatsCompletedEventHandler decreaseSocialStatsCompleted;
    
    /// CodeRemarks
    public event increaseMentalStatsCompletedEventHandler increaseMentalStatsCompleted;
    
    /// CodeRemarks
    public event decreaseMentalStatsCompletedEventHandler decreaseMentalStatsCompleted;
    
    /// CodeRemarks
    public event increaseEmotionalStatsCompletedEventHandler increaseEmotionalStatsCompleted;
    
    /// CodeRemarks
    public event decreaseEmotionalStatsCompletedEventHandler decreaseEmotionalStatsCompleted;
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// CodeRemarks
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// CodeRemarks
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getUserStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public userStats getUserStats(long iduser) {
        object[] results = this.Invoke("getUserStats", new object[] {
                    iduser});
        return ((userStats)(results[0]));
    }
    
    /// CodeRemarks
    public void getUserStatsAsync(long iduser) {
        this.getUserStatsAsync(iduser, null);
    }
    
    /// CodeRemarks
    public void getUserStatsAsync(long iduser, object userState) {
        if ((this.getUserStatsOperationCompleted == null)) {
            this.getUserStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserStatsOperationCompleted);
        }
        this.InvokeAsync("getUserStats", new object[] {
                    iduser}, this.getUserStatsOperationCompleted, userState);
    }
    
    private void OngetUserStatsOperationCompleted(object arg) {
        if ((this.getUserStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getUserStatsCompleted(this, new getUserStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/increasePhysicalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int increasePhysicalStats(int iduser, int increment) {
        object[] results = this.Invoke("increasePhysicalStats", new object[] {
                    iduser,
                    increment});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void increasePhysicalStatsAsync(int iduser, int increment) {
        this.increasePhysicalStatsAsync(iduser, increment, null);
    }
    
    /// CodeRemarks
    public void increasePhysicalStatsAsync(int iduser, int increment, object userState) {
        if ((this.increasePhysicalStatsOperationCompleted == null)) {
            this.increasePhysicalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincreasePhysicalStatsOperationCompleted);
        }
        this.InvokeAsync("increasePhysicalStats", new object[] {
                    iduser,
                    increment}, this.increasePhysicalStatsOperationCompleted, userState);
    }
    
    private void OnincreasePhysicalStatsOperationCompleted(object arg) {
        if ((this.increasePhysicalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.increasePhysicalStatsCompleted(this, new increasePhysicalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/decreasePhysicalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int decreasePhysicalStats(int iduser, int decrement) {
        object[] results = this.Invoke("decreasePhysicalStats", new object[] {
                    iduser,
                    decrement});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void decreasePhysicalStatsAsync(int iduser, int decrement) {
        this.decreasePhysicalStatsAsync(iduser, decrement, null);
    }
    
    /// CodeRemarks
    public void decreasePhysicalStatsAsync(int iduser, int decrement, object userState) {
        if ((this.decreasePhysicalStatsOperationCompleted == null)) {
            this.decreasePhysicalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndecreasePhysicalStatsOperationCompleted);
        }
        this.InvokeAsync("decreasePhysicalStats", new object[] {
                    iduser,
                    decrement}, this.decreasePhysicalStatsOperationCompleted, userState);
    }
    
    private void OndecreasePhysicalStatsOperationCompleted(object arg) {
        if ((this.decreasePhysicalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.decreasePhysicalStatsCompleted(this, new decreasePhysicalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/increaseSocialStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int increaseSocialStats(int iduser, int increment) {
        object[] results = this.Invoke("increaseSocialStats", new object[] {
                    iduser,
                    increment});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void increaseSocialStatsAsync(int iduser, int increment) {
        this.increaseSocialStatsAsync(iduser, increment, null);
    }
    
    /// CodeRemarks
    public void increaseSocialStatsAsync(int iduser, int increment, object userState) {
        if ((this.increaseSocialStatsOperationCompleted == null)) {
            this.increaseSocialStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincreaseSocialStatsOperationCompleted);
        }
        this.InvokeAsync("increaseSocialStats", new object[] {
                    iduser,
                    increment}, this.increaseSocialStatsOperationCompleted, userState);
    }
    
    private void OnincreaseSocialStatsOperationCompleted(object arg) {
        if ((this.increaseSocialStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.increaseSocialStatsCompleted(this, new increaseSocialStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/decreaseSocialStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int decreaseSocialStats(int iduser, int decrement) {
        object[] results = this.Invoke("decreaseSocialStats", new object[] {
                    iduser,
                    decrement});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void decreaseSocialStatsAsync(int iduser, int decrement) {
        this.decreaseSocialStatsAsync(iduser, decrement, null);
    }
    
    /// CodeRemarks
    public void decreaseSocialStatsAsync(int iduser, int decrement, object userState) {
        if ((this.decreaseSocialStatsOperationCompleted == null)) {
            this.decreaseSocialStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndecreaseSocialStatsOperationCompleted);
        }
        this.InvokeAsync("decreaseSocialStats", new object[] {
                    iduser,
                    decrement}, this.decreaseSocialStatsOperationCompleted, userState);
    }
    
    private void OndecreaseSocialStatsOperationCompleted(object arg) {
        if ((this.decreaseSocialStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.decreaseSocialStatsCompleted(this, new decreaseSocialStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/increaseMentalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int increaseMentalStats(int iduser, int increment) {
        object[] results = this.Invoke("increaseMentalStats", new object[] {
                    iduser,
                    increment});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void increaseMentalStatsAsync(int iduser, int increment) {
        this.increaseMentalStatsAsync(iduser, increment, null);
    }
    
    /// CodeRemarks
    public void increaseMentalStatsAsync(int iduser, int increment, object userState) {
        if ((this.increaseMentalStatsOperationCompleted == null)) {
            this.increaseMentalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincreaseMentalStatsOperationCompleted);
        }
        this.InvokeAsync("increaseMentalStats", new object[] {
                    iduser,
                    increment}, this.increaseMentalStatsOperationCompleted, userState);
    }
    
    private void OnincreaseMentalStatsOperationCompleted(object arg) {
        if ((this.increaseMentalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.increaseMentalStatsCompleted(this, new increaseMentalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/decreaseMentalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int decreaseMentalStats(int iduser, int decrement) {
        object[] results = this.Invoke("decreaseMentalStats", new object[] {
                    iduser,
                    decrement});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void decreaseMentalStatsAsync(int iduser, int decrement) {
        this.decreaseMentalStatsAsync(iduser, decrement, null);
    }
    
    /// CodeRemarks
    public void decreaseMentalStatsAsync(int iduser, int decrement, object userState) {
        if ((this.decreaseMentalStatsOperationCompleted == null)) {
            this.decreaseMentalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndecreaseMentalStatsOperationCompleted);
        }
        this.InvokeAsync("decreaseMentalStats", new object[] {
                    iduser,
                    decrement}, this.decreaseMentalStatsOperationCompleted, userState);
    }
    
    private void OndecreaseMentalStatsOperationCompleted(object arg) {
        if ((this.decreaseMentalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.decreaseMentalStatsCompleted(this, new decreaseMentalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/increaseEmotionalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int increaseEmotionalStats(int iduser, int increment) {
        object[] results = this.Invoke("increaseEmotionalStats", new object[] {
                    iduser,
                    increment});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void increaseEmotionalStatsAsync(int iduser, int increment) {
        this.increaseEmotionalStatsAsync(iduser, increment, null);
    }
    
    /// CodeRemarks
    public void increaseEmotionalStatsAsync(int iduser, int increment, object userState) {
        if ((this.increaseEmotionalStatsOperationCompleted == null)) {
            this.increaseEmotionalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnincreaseEmotionalStatsOperationCompleted);
        }
        this.InvokeAsync("increaseEmotionalStats", new object[] {
                    iduser,
                    increment}, this.increaseEmotionalStatsOperationCompleted, userState);
    }
    
    private void OnincreaseEmotionalStatsOperationCompleted(object arg) {
        if ((this.increaseEmotionalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.increaseEmotionalStatsCompleted(this, new increaseEmotionalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/decreaseEmotionalStats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int decreaseEmotionalStats(int iduser, int decrement) {
        object[] results = this.Invoke("decreaseEmotionalStats", new object[] {
                    iduser,
                    decrement});
        return ((int)(results[0]));
    }
    
    /// CodeRemarks
    public void decreaseEmotionalStatsAsync(int iduser, int decrement) {
        this.decreaseEmotionalStatsAsync(iduser, decrement, null);
    }
    
    /// CodeRemarks
    public void decreaseEmotionalStatsAsync(int iduser, int decrement, object userState) {
        if ((this.decreaseEmotionalStatsOperationCompleted == null)) {
            this.decreaseEmotionalStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndecreaseEmotionalStatsOperationCompleted);
        }
        this.InvokeAsync("decreaseEmotionalStats", new object[] {
                    iduser,
                    decrement}, this.decreaseEmotionalStatsOperationCompleted, userState);
    }
    
    private void OndecreaseEmotionalStatsOperationCompleted(object arg) {
        if ((this.decreaseEmotionalStatsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.decreaseEmotionalStatsCompleted(this, new decreaseEmotionalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// CodeRemarks
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class userStats {
    
    private int physicalStatsField;
    
    private int mentalStatsField;
    
    private int socialStatsField;
    
    private int emotionalStatsField;
    
    /// <remarks/>
    public int physicalStats {
        get {
            return this.physicalStatsField;
        }
        set {
            this.physicalStatsField = value;
        }
    }
    
    /// <remarks/>
    public int mentalStats {
        get {
            return this.mentalStatsField;
        }
        set {
            this.mentalStatsField = value;
        }
    }
    
    /// <remarks/>
    public int socialStats {
        get {
            return this.socialStatsField;
        }
        set {
            this.socialStatsField = value;
        }
    }
    
    /// <remarks/>
    public int emotionalStats {
        get {
            return this.emotionalStatsField;
        }
        set {
            this.emotionalStatsField = value;
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void getUserStatsCompletedEventHandler(object sender, getUserStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getUserStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getUserStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public userStats Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((userStats)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void increasePhysicalStatsCompletedEventHandler(object sender, increasePhysicalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class increasePhysicalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal increasePhysicalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void decreasePhysicalStatsCompletedEventHandler(object sender, decreasePhysicalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class decreasePhysicalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal decreasePhysicalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void increaseSocialStatsCompletedEventHandler(object sender, increaseSocialStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class increaseSocialStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal increaseSocialStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void decreaseSocialStatsCompletedEventHandler(object sender, decreaseSocialStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class decreaseSocialStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal decreaseSocialStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void increaseMentalStatsCompletedEventHandler(object sender, increaseMentalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class increaseMentalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal increaseMentalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void decreaseMentalStatsCompletedEventHandler(object sender, decreaseMentalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class decreaseMentalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal decreaseMentalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void increaseEmotionalStatsCompletedEventHandler(object sender, increaseEmotionalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class increaseEmotionalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal increaseEmotionalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void decreaseEmotionalStatsCompletedEventHandler(object sender, decreaseEmotionalStatsCompletedEventArgs e);

/// CodeRemarks
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class decreaseEmotionalStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal decreaseEmotionalStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// CodeRemarks
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
